development:
  adapter: postgresql
  encoding: utf8
  database: xxxxxxx
  username: xxxxxxx
  password: xxxxxxx
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: xxxxxxx
  username: xxxxxxx
  password: xxxxxxx
  pool: 5
  port: 5432
